config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, length: { in: 1..50 }
  validates :text, length: { maximum: 300 }
  validates :user_id, presence: true

  def self.user_recipes_get(user_bigint)
    Recipe.where(user_id: user_bigint)
  end

  def self.user_recipe_get(user_bigint, recipe_bigint)
    Recipe.find_by(id: recipe_bigint, user_id: user_bigint)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :lockable, and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable, :trackable, :timeoutable

  with_options presence: true, uniqueness: true do
    validates :email
    validates :name, length: { in: 5..15, allow_blank: true }, format: { with: /\A[a-z][a-z0-9]+\z/i, message: 'は最初の文字は半角英字、その後は半角英数を使って下さい', allow_blank: true }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.user_recipes_get(current_user.id)
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @recipe = Recipe.user_recipe_get(current_user.id, params[:id])
    redirect_to recipes_path, status: :found, alert: 'レシピにアクセス出来ません' if @recipe.nil?
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    recipe = Recipe.new(recipe_params)
    if recipe.save
      redirect_to recipes_path, notice: 'レシピを登録完了！'
    else
      flash[:alert] = 'レシピの登録に失敗しました。'
      render :new
    end
  end

  def update
    recipe = Recipe.find(params[:id])
    if recipe.update(recipe_params)
      redirect_to recipe_path(params[:id]), notice: 'レシピを変更しました。'
    else
      flash[:alert] = 'レシピの登録に失敗しました。'
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    recipe_name = @recipe.name
    @recipe.destroy!
    redirect_to recipes_path, notice: "#{recipe_name}のレシピを削除しました"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :text).merge(user_id: current_user.id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Myrecipe</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand navbar-dark" style="background-color: #7C0A02;">
      <div class="container-fluid">
        <%= link_to "MYREPI", root_path, class: "navbar-brand"%>
        <ul class="navbar-nav ml-auto">
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                <li><%= link_to 'アカウント編集', edit_user_registration_path, class: "dropdown-item" %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
              </ul>
            </li>
          <% else %>
            <li class="nav-item"><%= link_to '新規登録', new_user_registration_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% if flash[:notice] %>
      <p>Notice: <%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p>Alert: <%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/recipes/_recipe.html.erb
<tr>
	<td>
		<!-- Button trigger modal -->
		<button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#staticBackdrop-<%= recipe.id %>">
			<%= recipe.name %>
		</button>

		<!-- Modal -->
		<div class="modal fade" id="staticBackdrop-<%= recipe.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdrop-<%= recipe.id %>Label" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="staticBackdrop-<%= recipe.id %>Label"><%= recipe.name %>の作り方</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						<p class="lead">
							<%= safe_join(recipe.text.split("\n"),tag(:br)) %>
						</p>
						<h6 class="mb-1">最近作った日</h6>
						<% unless recipe.recent_at.nil? %>
							<p><%= recipe.recent_at %></p>
						<% else %>
							<p>No Data</p>
						<% end %>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
						<%= link_to "編集", edit_recipe_path(recipe.id), class: 'btn btn-primary' %>
						<%= link_to "削除",recipe_path(recipe.id), method: :delete, data: { confirm: recipe.name + "のレシピを削除しますか？"}, class: 'btn btn-danger' %>
					</div>
				</div>
			</div>
		</div>
	</td>
	<td>
	<% unless recipe.recent_at.nil? %>
		<%= recipe.recent_at %>
	<% else %>
		No Data
	<% end %>
	</td>
</tr>

app/views/recipes/_recipeform.html.erb
<%= form_with model: @recipe, local: true do |f| %>
	<div class="row">
    <div class="mb-3">
      <%= f.label :name, '料理名', class: 'form-label'  %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="mb-3">
      <%= f.label :text, '作り方', class: 'form-label'  %>
      <%= f.text_area :text, class: 'form-control', rows: 10 %>
    </div>
  </div>
  <div class="row mt-4">
    <div class="d-grid gap-2 col-4 mx-auto">
      <%= link_to "戻る", :back, class: 'btn btn-secondary' %>
    </div>
    <div class="d-grid gap-2 col-4 mx-auto">
      <%= f.submit "登録", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="container">
	<h1>編集</h1>
	<hr>
	<h3><%= @recipe.name %>の作り方</h1>
	<%= render partial: 'recipeform', locals: { recipe: @recipe } %>
</div>

app/views/recipes/index.html.erb
<div class="container">
	<div class="row">
		<% unless @recipes.blank? %>
		<table class="table">
			<thead>
				<tr>
					<th scope="col">レシピ名</th>
					<th scope="col">最近作った日</th>
				</tr>
			</thead>
			<tbody>
				<%= render @recipes %>
			</tbody>
		</table>
	</div>
	<% else %>
		<p>早速レシピを登録しましょう！</p>
	<% end %>
	<div class="row">
	<%= link_to new_recipe_path do %>
		<button type="button" class="btn btn-primary">新規作成</button>
	<% end %>
	</div>
</div>

app/views/recipes/new.html.erb
<div class="container">
	<h1>レシピ新規登録</h1>
	<%= render 'recipeform' %>
</div>

app/views/recipes/show.html.erb
<div class="container">
	<div class="px-3 mb-4 bg-light rounded-1">
		<div class="container-fluid py-5">
			<h1 class="display-5 fw-bold"><%= @recipe.name %>の作り方</h3>
			<p class="lead">
				<%= safe_join(@recipe.text.split("\n"),tag(:br)) %>
			</p>
			<h6 class="mb-1">最近作った日</h5>
			<% unless @recipe.recent_at.nil? %>
				<%= @recipe.recent_at %>
			<% else %>
				No Data
			<% end %>
		</div>
	</div>


	<div class="row">
		<div class="d-grid gap-2 col-4 mx-auto">
			<%= link_to "戻る", recipes_path, class: 'btn btn-secondary' %>
		</div>
		<div class="d-grid gap-2 col-4 mx-auto">
			<%= link_to "編集", edit_recipe_path, class: 'btn btn-primary' %>
		</div>
		<div class="d-grid gap-2 col-4 mx-auto">	
		<%= link_to "削除",recipe_path(@recipe), method: :delete, data: { confirm: @recipe.name + "のレシピを削除しますか？"}, class: 'btn btn-danger' %>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<div>
	<%= link_to "レシピ一覧", recipes_path %>
</div>